### ISSUE TITLE
Deprecation: alias this for classes/interfaces is deprecated

### ISSUE THREAD

**Issue by GrimMaple** [MyLittleRobo/icontheme#2]
In DMD 2.103.1 there's a deprecation warning:
```
C:\Users\grimm\AppData\Local\dub\packages\icontheme-1.2.3\icontheme\source\icontheme\file.d(547,5): Deprecation: alias this for classes/interfaces is deprecated
```

**Comment by FreeSlave** [comment]
Honestly I don't know how to fix it without breaking/revamping the code.
The solution proposed in the [dmd changelog](https://dlang.org/changelog/2.103.0.html#dmd.deprecate-alias-this-for-classes) didn't work for me.
It also looks wrong and insufficient at all.

**Comment by GrimMaple** [comment]
As much as I hate the idea of breaking code, there doesn't seem to be any reasonable solution beside breaking the code and bumping the version number.
This has to be done eventually anyway now.

**Comment by GrimMaple** [comment]
Walter said he might "undeprecate" alias this. But I don't know if he will.

**Comment by FreeSlave** [comment]
Can you give a link to discussion?

**Comment by GrimMaple** [comment]
> Can you give a link to discussion?

https://forum.dlang.org/post/u4banl$e4g$1@digitalmars.com

**Comment by GrimMaple** [comment]
Apparently, alias this was indeed undeprecated https://github.com/dlang/dmd/pull/15326
